### ISSUE TITLE
Not Working On Some Devices 

### ISSUE THREAD

**Issue by Scienticious** [talhahasanzia/android-encryption-helper#12]
05-25 10:05:53.285 8499-8499/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pacakge.name PID: 8499
    java.lang.RuntimeException: Unable to create application com..pacakge.name java.security.ProviderException: Failed to load generated key pair from keystore
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5451)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
 Caused by: java.security.ProviderException: Failed to load generated key pair from keystore
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:518)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:470)
  at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699)
        at com.thz.keystorehelper.KeystoreHelper.createKeys(KeystoreHelper.java:199)
        at com.thz.keystorehelper.KeystoreHelper.encryptString(KeystoreHelper.java:71)
        at com.thz.keystorehelper.KeyStoreManager.encryptData(KeyStoreManager.java:90)
        at com.islamiccenterapps.wicapp.root.IcaApp.onCreate(IcaApp.java:44)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6186) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
     Caused by: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:230)
   at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:509)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:470) 
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699) 
        at com.thz.keystorehelper.KeystoreHelper.createKeys(KeystoreHelper.java:199) 
        at com.thz.keystorehelper.KeystoreHelper.encryptString(KeystoreHelper.java:71) 
        at com.thz.keystorehelper.KeyStoreManager.encryptData(KeyStoreManager.java:90) 
        at com.islamiccenterapps.wicapp.root.IcaApp.onCreate(IcaApp.java:44) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
   at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6186) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
     Caused by: android.security.KeyStoreException: -22
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:676)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:231

**Comment by talhahasanzia** [comment]
I can confirm that this was device specific issue. Which was reproduced on Le Eco Le 2 running Nougat. The issue disappeared when the device was updated to Oreo.

This crash is now handled in [Release 0.3.1](https://github.com/talhahasanzia/android-encryption-helper/releases/tag/0.3.1). Please update the library version. 

Thanks!
